name: date_time
description: Package to work with Date & Time in separation and with its Ranges.
version: 0.8.0
homepage: https://github.com/AndrewPiterov/date_time

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  quiver: ^3.1.0
  intl: ^0.17.0
  clock: ^1.1.0

dev_dependencies:
  given_when_then_unit_test: ^0.1.0
  lint: ^1.10.0
  shouldly: ^0.5.0+1
  test: ^1.20.1
