name: date_time
description: Package to work with Date & Time in separation and with its Ranges.
version: 0.6.0
homepage: https://github.com/AndrewPiterov/date_time

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  quiver: ^3.0.1+1
  intl: ^0.17.0

dev_dependencies:
  given_when_then_unit_test: ^0.0.7
  lint: ^1.8.1
  shouldly: ^0.2.4
  test: ^1.20.1
